### ISSUE TITLE
本地视频播放疑惑

### ISSUE THREAD

**Issue by liuzhuoming** [CCVideo/VOD_iOS_SDK#3]
我将视频下载到本地一个目录后，如何播放该文件？

DWPlayerView 提供了一个 方法来播放本地视频
`-(void)playLocalVideo:(DWDownloadModel *)downloadModel;`

对于需要的参数DWDownloadModel ，除了下面的方法我没有找到其他生成的函数。 于是我除了loaclPath和UserId 其他都是乱填，居然也能播放。但是为了安全起见，我觉得需要一个更合理的构造方法。

```
-(DWDownloadModel *)migrateDownloadTask:(NSString *)loaclPath
               DownloadUrl:(NSString *)downloadUrl
                 MediaType:(NSString *)mediaType
                   Quality:(NSString *)quality
                      Desp:(NSString *)desp
                    VRMode:(BOOL)vrMode
                OthersInfo:(NSDictionary *)othersInfo
                    UserId:(NSString *)userId
                   VideoId:(NSString *)videoId
        TotalBytesWritten:(int64_t)totalBytesWritten TotalBytesExpectedToWrite:(int64_t)totalBytesExpectedToWrite;
```

**Comment by zhaowl123** [comment]
此方法是3.x升级4.0.0及以后需要调用的，目的是为了防止3.x版本下载的视频丢失，无法播放的问题。如果没有继承3.x的版本，此方法不需要使用的。
对于正常的下载流程，通过DWDownloadSessionManager初始化DWDownloadModel对象，完成下载，DWPlayerView调用playLocalVideo:方法即可。具体详实方式可以参考下[2.继承指南](https://github.com/CCVideo/VOD_iOS_SDK/wiki/2.集成指南)中的 3.2下载功能。

**Comment by liuzhuoming** [comment]
所以我缓存完视频，还应该保存这个下载链接，以便从DWDownloadSessionManager换出DWDownloadModel？

**Comment by zhaowl123** [comment]
缓存通过DWDownloadSessionManager来缓存，DWDownloadSessionManager对象本身持有了一个DWDownloadModel的数据，为什么要保存链接重新换出DWDownloadModel呢？具体实现可以参考下我们demo中的下载流程。

**Comment by liuzhuoming** [comment]
demo中的逻辑对我来说不是很合适，它将所有的视频都缓存在一起。而且我习惯从原来3.x的下载逻辑，下载好了之后将文件移动到自定义的路径，然后从DWDownloadSessionManager里面将下载模型删除。
还是希望提供本地路径进行播放的方法。

**Comment by zhaowl123** [comment]
4.x以后的下载逻辑统一转移到了SDK中进行管理。如果您觉得使用方式有问题或满足不了项目需求，可以联系下我们的售后或者技术支持反馈下情况。
